version: 2

project_name: xget

before:
  hooks:
    - go mod tidy

builds:
  - id: xget
    main: ./cmd/xget
    binary: xget
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/camalot/xget/internal/version.Version={{.Version}}

archives:
  - id: xget
    formats: [zip]
    format_overrides:
      - goos: linux
        formats: [tar.gz]
      - goos: darwin
        formats: [tar.gz]
    wrap_in_directory: false
    files:
      - README.md
      - LICENSE
      - xget.1

checksum:
  name_template: checksums.txt

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

sboms:
  - id: xget-sbom
    artifacts: archive

snapshot:
  version_template: "{{ .Tag }}-next"

scoops:
  - name: xget
    repository:
      owner: camalot
      name: xget-scoop-bucket # The repo where you want the manifest pushed
    commit_author:
      name: CI Bot
      email: bot@example.com
    homepage: "https://github.com/camalot/xget"
    description: "Easy pre-built binary installation for your favorite tools."
    license: MIT

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
