version: 2

project_name: xget

release:
  prerelease: auto

before:
  hooks:
    - go mod tidy

builds:
  - id: xget
    main: ./cmd/xget
    binary: xget
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/camalot/xget/internal/cli.version={{.Version}}
      - -X github.com/camalot/xget/internal/cli.commit={{.ShortCommit}}
      - -X github.com/camalot/xget/internal/cli.date={{.Date}}
archives:
  - id: xget
    formats: [zip]
    format_overrides:
      - goos: linux
        formats: [tar.gz]
      - goos: darwin
        formats: [tar.gz]
    wrap_in_directory: false
    files:
      - README.md
      - LICENSE
      - xget.1

checksum:
  name_template: checksums.txt

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

sboms:
  - id: xget-sbom
    artifacts: archive

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
