---

version: '3'
vars: {}

tasks:
  build:
    desc: Build the project
    cmds:
      - echo "Building the project..."
      - mkdir -p bin
      - go mod tidy
      - golangci-lint run ./...
      - goreleaser build --snapshot --clean
      - go vet ./...
      - gofmt -l .
      - go test ./...


  ironstate:
    cmds:
      - .\dist\xget_windows_amd64_v1\xget.exe tacocontent/ironstate --to=./bin --verify-sha256 --ignore-asset=.sbom.json