source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "~> 0.10"
gem "rouge", "~> 4.0"

group :jekyll_plugins do
  gem "jekyll-remote-theme", "~> 0.5"
  gem "jekyll-seo-tag", "~> 2.9"
  gem "jekyll-gfm-admonitions", "~> 1.4"
end
