---
name: 'Test xget Action'
on:
  workflow_dispatch: {}
permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: xget sharkdp/bat
        uses: camalot/xget-action@main
        with:
          token: ${{ github.token }}
          xget-version: v2.0.0-beta
          package: sharkdp/bat
          asset-filters: ~gnu\.tar\.gz$

      - name: Verify bat Installation
        run: |
          bat --version
          which bat
          bat .github/workflows/xget.yml

      - name: Verify xget Installation
        run: |
          xget version
          which xget
        
      - name: xget bschaatsbergen/cidr
        uses: camalot/xget-action@main
        with:
          token: ${{ github.token }}
          xget-version: v2.0.0-beta
          package: bschaatsbergen/cidr
          asset-filters: ~\.tar\.gz$


      - name: Verify cidr Installation
        run: |
          cidr --version
          which cidr
          cidr explain 10.0.0.0/16 | bat
          cidr count 10.0.0.0/20 | bat
